---
title: "Push Compute to Server"
author: "Alex Gold"
date: "11/7/2019"
output: html_document
---
```{r}
library(DBI)
library(glue)
library(dplyr)
```

```{r}
con <- dbConnect(odbc::odbc(), 
                 Driver="postgresql", 
                 Server = "localhost", 
                 Port = "5432", 
                 Database = "postgres", 
                 UID = "postgres", 
                 PWD = Sys.getenv("db_pass"), 
                 BoolsAsChar = "", 
                 timeout = 10)
dbExecute(con, "SET search_path=london;")
```







Use `dplyr` to do computation.
```{r}
(df <- tbl(con, "plan"))
```



















Push Compute to Server 1: Pull smallest set possible into db.
```{r}
time <- system.time(
  dat <- df %>%
    group_by(permission_type) %>%
    summarize(n(), 
              mean(total_time), 
              median(total_time), 
              sd(total_time)) %>%
    collect()
)
dat
```















It's way faster.
```{r}
time_bad <- system.time(
  df %>%
    # Import data first = bad
    collect() %>%
    group_by(permission_type) %>%
    summarize(mean(total_time), 
              median(total_time), 
              sd(total_time))
)

time
time_bad
```
















Push compute to server 2: Use packages to do work.

















Dbplot
```{r}
dbplot::dbplot_line(df,
                    x = permission_financial_year,
                    y = mean(proposed_total_floorspace)) +
  xlab("Year") +
  ylab("Average Floorspace") +
  scale_y_continuous(labels = scales::comma) +
  ggthemes::theme_clean()
```

















modeldb
```{r}
(lin_reg <- df %>%
  select(total_time, 
         start_month, 
         proposed_total_floorspace) %>%
  modeldb::add_dummy_variables(start_month, auto_values = TRUE) %>%
  modeldb::linear_regression_db(total_time, auto_count = TRUE))
```














Write predictions back to data and get RMSE
```{r}
(non_months <- glue::glue(
  "UPDATE plan
  SET pred_total_time = {lin_reg$`(Intercept)`} +
  {lin_reg$proposed_total_floorspace} + proposed_total_floorspace;"))

dbSendQuery(con, "ALTER TABLE plan DROP COLUMN IF EXISTS pred_total_time;")
dbSendQuery(con, "ALTER TABLE plan ADD COLUMN pred_total_time numeric;")
dbSendQuery(con, non_months)


months <- stringr::str_match(names(lin_reg), "start_month_(\\d+)")[,2] %>%
  purrr::keep(~!is.na(.))

month_sql <- "UPDATE plan
    SET pred_total_time = pred_total_time + {month_val}
    WHERE start_month = {month};"

purrr::walk(months, function(month) {
  month_val <- lin_reg[[paste0("start_month_", month)]]
  dbGetQuery(con, glue::glue(month_sql))
})
```






Compute RMSE
```{r}
df %>%
  summarize(rmse = sqrt(mean((pred_total_time - total_time)^2)))
```
